version: "3.9"
services:
  db:
    image: postgres:16
    container_name: av_db
    restart: always
    environment:
      POSTGRES_USER: avuser
      POSTGRES_PASSWORD: avpassword
      POSTGRES_DB: av
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
